Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/GlobalVars:
  Exclude:
    - 'main.rb'
    - 'core/config.rb'
    - 'core/database.rb'

Lint/Eval:
  Exclude:
    - 'main.rb'
    - 'Rakefile'
