---
:command_codes:
  "393": rpl_users
  "251": rpl_luserclient
  "365": rpl_endoflinks
  "394": rpl_endofusers
  "252": rpl_luserop
  "366": rpl_endofnames
  "421": err_unknowncommand
  "395": rpl_nousers
  "253": rpl_luserunknown
  "367": rpl_banlist
  "422": err_nomotd
  "254": rpl_luserchannels
  "451": err_notregistered
  "368": rpl_endofbanlist
  "423": err_noadmininfo
  "255": rpl_luserme
  "369": rpl_endofwhowas
  "424": err_fileerror
  "481": err_noprivileges
  "256": rpl_adminme
  "311": rpl_whoisuser
  "482": err_chanoprivsneeded
  "312": rpl_whoisserver
  "341": rpl_inviting
  "313": rpl_whoisoperator
  "483": err_cantkillserver
  "200": rpl_tracelink
  "314": rpl_whowasuser
  "342": rpl_summoning
  "315": rpl_endofwho
  "371": rpl_info
  "201": rpl_traceconnecting
  "372": rpl_motd
  "202": rpl_tracehandshake
  "317": rpl_whoisidle
  "203": rpl_traceunknown
  "318": rpl_endofwhois
  "374": rpl_endofinfo
  "204": rpl_traceoperator
  "401": err_nosuchnick
  "319": rpl_whoischannels
  "261": rpl_tracelog
  "375": rpl_motdstart
  "205": rpl_traceuser
  "402": err_nosuchserver
  "376": rpl_endofmotd
  "431": err_nonicknamegiven
  "206": rpl_traceserver
  "403": err_nosuchchannel
  "432": err_erroneusnickname
  "404": err_cannotsendtochan
  "461": err_needmoreparams
  "433": err_nicknameinuse
  "208": rpl_tracenewtype
  "405": err_toomanychannels
  "406": err_wasnosuchnick
  "462": err_alreadyregistred
  "407": err_toomanytargets
  "491": err_nooperhost
  "463": err_nopermforhost
  "321": rpl_liststart
  "436": err_nickcollision
  "464": err_passwdmismatch
  "322": rpl_list
  "409": err_noorigin
  "351": rpl_version
  "465": err_yourebannedcreep
  "323": rpl_listend
  "352": rpl_whoreply
  "324": rpl_channelmodeis
  "381": rpl_youreoper
  "353": rpl_namreply
  "211": rpl_statslinkinfo
  "467": err_keyset
  "382": rpl_rehashing
  "212": rpl_statscommands
  "241": rpl_statslline
  "213": rpl_statscline
  "242": rpl_statsuptime
  "214": rpl_statsnline
  "411": err_norecipient
  "215": rpl_statsiline
  "412": err_notexttosend
  "243": rpl_statsoline
  "216": rpl_statskline
  "413": err_notoplevel
  "244": rpl_statshline
  "441": err_usernotinchannel
  "414": err_wildtoplevel
  "442": err_notonchannel
  "300": rpl_none
  "218": rpl_statsyline
  "471": err_channelisfull
  "443": err_useronchannel
  "301": rpl_away
  "219": rpl_endofstats
  "472": err_unknownmode
  "444": err_nologin
  "302": rpl_userhost
  "473": err_inviteonlychan
  "331": rpl_notopic
  "445": err_summondisabled
  "303": rpl_ison
  "474": err_bannedfromchan
  "332": rpl_topic
  "446": err_usersdisabled
  "501": err_umodeunknownflag
  "475": err_badchannelkey
  "305": rpl_unaway
  "502": err_usersdontmatch
  "306": rpl_nowaway
  "221": rpl_umodeis
  "391": rpl_time
  "364": rpl_links
  "392": rpl_usersstart
